name: Deploy to Vercel

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checks out your repository
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v3 # Uses a specific GitHub Action for Vercel deployment
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          # Optional: specify the production branch if it's not main
          # vercel-args: '--prod' 
